import { CardPlay } from './cardplay';

export const CARDARRAY: CardPlay[] = [
{
    /* Contains exactly 10 points. */
    /* Part #1 will be re-used in playing a 10set. */
    /* Part #2 will be replaced by values from actual or mock-cards. */

    /* pt 1 */
    /* Part #1 */
    PointNo: 1,                     /* Pre-set values from 1 to 10. */
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight: 0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    /* Part #2 */
    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 2 */
    PointNo: 2,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 3 */
    PointNo: 3,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 4 */
    PointNo: 4,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 5 */
    PointNo: 5,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 6 */
    PointNo: 6,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 7 */
    PointNo: 7,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 8 */
    PointNo: 8,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 9 */
    PointNo: 9,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
},
{
    /* pt 10 */
    PointNo: 10,
    CountAsked:  0,
    CountAskedVerify:  0,
    CountRight:  0,
    CountRightVerify: 0,
    IsPassed: 0,
    IsReview: 0,
    IsVerified:  0,
    Score:  0,
    ScoreVerify: 0,

    PlayTenSetId: 0,
    PointId: 0,
    IsCorrect: 0,
    LevelAward: 0,
    LevelAwardScore: 0,
    LevelBoost: 0,
    LevelBoostScore: 0,
    LevelImage: 0,
    LevelName: "",
    LevelNoWon: 0,
    PlayId: 0,
    PlayerName: "",
    PointName: "",
    Q1Ans1Act: "",
    Q1Ans2Alt: "",
    Q1Ans3Alt: "",
    Q1Ans4Alt: "",
    Q1Question: "",
    Q1TypeId: 0,
    Q2Ans1Act: "",
    Q2Ans2Alt: "",
    Q2Ans3Alt: "",
    Q2Ans4Alt: "",
    Q2Question: "",
    Q2TypeId: 0,
    Q3Ans1Act: "",
    Q3Ans2Alt: "",
    Q3Ans3Alt: "",
    Q3Ans4Alt: "",
    Q3Question: "",
    Q3TypeId: 0,
    SectionId: 0,
    S1Statement: "",
    S2Statement: "",  
    ToVerify: 0,
}];
